spring:
  devtools:
    restart:
      enabled: false
  profiles:
    active: dev

# 日志配置
logging:
  level:
    org.apache.http: info
    org.springframework: info

# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 搜索指定包别名
  typeAliasesPackage: com.wayn.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

ipProxy:
  wanbian:
    api: xxx

tencent:
  map:
    host: https://apis.map.qq.com
    key: xxx
    secretKey: xxx
